- name: Configure backend servers
  hosts: backend
  become: yes
  roles:
    - common
    - backend

- name: Configure frontend servers
  hosts: frontend
  become: yes
  roles:
    - common
    - frontend
